### PR TITLE
[Contrib] Using bash on windows 10

### PR DESCRIPTION
**Pull request by ventilooo**
Short guide no enable bash on windows 10 in order to be able to install nit on windows 10 using the ubuntu/debian way. (once bash is installed)

As announced [here](https://github.com/nitlang/nit/issues/2263)

### CODE REVIEW

**Comment by privat** [comment]
Can someone with a windows OS installed can comment on it? @xymus @BlackMinou ?

**Comment by xymus** [comment]
The steps should work, but it's generic to activate bash on Windows, nothing is specific to Nit except for the last line. It doesn't belong on this page.

**In fact, the guide appears to have been plagiarized directly from http://www.windowscentral.com/how-install-bash-shell-command-line-windows-10.**

Anyway, there's no need to plagiarize or recopy the guide here, referring to the official MSDN doc at  https://msdn.microsoft.com/en-us/commandline/wsl/install_guide is appropriate.

**Comment by ventilooo** [comment]
Just pointing to the page, for the activations steps and indicating to follow the Debian/Ubuntu should work ?

**Comment by xymus** [comment]
Yes, but point to the official doc and keep it simple, there's like 3 steps: install bash, open bash, install Nit for Ubuntu.

**Pull request closed without merging**
